workflows:
  android-debug-workflow:
    name: Android Debug Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        # Environment variables can be defined here if needed.
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing dependencies..."
          cd android && ./gradlew dependencies
      - name: Run debug build
        script: |
          echo "Building the app..."
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - nsonu398@gmail.com # Replace with your email
